# **DAY 12: ASSIGNMENT 10 (dummy variables concept and one-hot-encoding)**


# **DATE: 10 JUNE 2021**

# **AUTHOR: AAMIR P**

# **REG. ID.: GO_STP_7724**

**Q1) Discuss the concept of One-Hot-Encoding, Multicollinearity and the Dummy Variable Trap. What is Nominal and Ordinal Variables ?**

A one hot encoding is a representation of categorical variables as binary vectors. It is called one-hot because only one bit is “hot” or TRUE at any time. In short, categorical to numerical form.

Multicollinearity occurs when two or more independent variables are highly correlated with one another in a regression model.

A dummy variable is a numerical variable used in regression analysis to represent subgroups of the sample. A dummy variable is a variable that takes values of 0 and 1, where the values indicate the presence or absence of something.

A nominal variable is a type of variable that is used to name, label or categorize particular attributes that are being measured

An ordinal variable is a categorical variable for which the possible values are ordered.

**2)Salary Dataset of 52 professors having categorical columns. Apply dummy variables concept and one-hot-encoding on categorical columns.**

In [15]:
import pandas as pd
import numpy as np

In [18]:
url = "https://data.princeton.edu/wws509/datasets/salary.dat"
df=pd.read_csv(url,delim_whitespace=True) #The url is read directly. delim_whitespace ignores continuos whitespaces.

**DUMMY VARIABLES**

In [19]:
pd.get_dummies(df,columns=['yr','yd','sl']).head() #Data is manipulated and converted from categorical to numerical. We have choose the columns heding to create it's dummy

       sx    rk         dg  yr_0  ...  sl_33696  sl_35350  sl_36350  sl_38045
0    male  full  doctorate     0  ...         0         0         1         0
1    male  full  doctorate     0  ...         0         1         0         0
2    male  full  doctorate     0  ...         0         0         0         0
3  female  full  doctorate     0  ...         0         0         0         0
4    male  full    masters     0  ...         1         0         0         0

[5 rows x 101 columns]

In [20]:
#Let us reduce the extra columns by using drop function
pd.get_dummies(df,columns=['yr','yd','sl'],drop_first=True).head()

       sx    rk         dg  yr_1  ...  sl_33696  sl_35350  sl_36350  sl_38045
0    male  full  doctorate     0  ...         0         0         1         0
1    male  full  doctorate     0  ...         0         1         0         0
2    male  full  doctorate     0  ...         0         0         0         0
3  female  full  doctorate     0  ...         0         0         0         0
4    male  full    masters     0  ...         1         0         0         0

[5 rows x 98 columns]

**ONE HOT ENCODING**

In [24]:
from sklearn.preprocessing import OneHotEncoder #raw feature to representation
from sklearn.compose import ColumnTransformer #Applies transformers to columns of an array or pandas DataFrame.
CT=ColumnTransformer([('encoder',OneHotEncoder(),[0,1,3])], remainder='passthrough') # remainder='passthrough' will mean that all columns not specified in the list of “transformers” will be passed through without transformation, instead of being dropped.
data= np.array(CT.fit_transform(df), dtype=int)
print(data[:7])

[[    0     1     0     0     1     1     0    25    35 36350]
 [    0     1     0     0     1     1     0    13    22 35350]
 [    0     1     0     0     1     1     0    10    23 28200]
 [    1     0     0     0     1     1     0     7    27 26775]
 [    0     1     0     0     1     0     1    19    30 33696]
 [    0     1     0     0     1     1     0    16    21 28516]
 [    1     0     0     0     1     0     1     0    32 24900]]